version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: iot-postgres
    environment:
      POSTGRES_USER: vi_user
      POSTGRES_PASSWORD: vi_pass
      POSTGRES_DB: vi_graphs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: iot-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: iot-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  
  kafka-init:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    entrypoint: [ "sh", "-c", "apk add --no-cache bash && \
      wget -qO- https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /wait-for-it.sh && \
      chmod +x /wait-for-it.sh && \
      /wait-for-it.sh kafka:9092 --timeout=60 -- \
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic test-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1" ]
  
  collector:
    build:
      context: .
      dockerfile: collector/Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
      MQTT_HOST: test.mosquitto.org
      MQTT_TOPIC: test/vi-sample
    depends_on:
      - kafka

  processor:
    build:
      context: .
      dockerfile: processor/Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: test-topic
      DATABASE_URL: postgres://vi_user:vi_pass@postgres:5432/vi_graphs
    depends_on:
      - kafka
      - postgres

volumes:
  pgdata:
