[package]
name = "collector"
version = "0.1.0"
edition = "2024"


[dependencies]
rdkafka = { version = "0.36", features = ["cmake-build"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"